andreoliwa/nitpick

flake8_nitpick/config.py

In our projects the `root_dir` is where django's `manage.py` lives, but `pyproject.toml` lives in `root_dir.parent`.

Allow pyproject.toml to be located in root dir's parents

---

.travis.yml

[semantic-release]: node version >=8.16 is required. Found v8.12.0.
See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md for more details and solutions.
Script failed with status 1

ci: upgrade NodeJS

---

.pre-commit-config.yaml
.travis.yml
CONTRIBUTING.rst
docs/defaults.rst
docs/generate_rst.py
poetry.lock
pyproject.toml
setup.cfg
styles/flake8.toml
styles/python39.toml

feat: drop support for Python 3.5

---

Makefile
docs/source/nitpick.plugins.info.rst
docs/source/nitpick.plugins.rst
poetry.lock
pyproject.toml
setup.cfg
src/nitpick/cli.py
src/nitpick/core.py
src/nitpick/generic.py
src/nitpick/plugins/__init__.py
src/nitpick/plugins/base.py
src/nitpick/plugins/info.py
src/nitpick/plugins/json.py
src/nitpick/plugins/pre_commit.py
src/nitpick/plugins/pyproject_toml.py
src/nitpick/plugins/setup_cfg.py
src/nitpick/plugins/text.py
src/nitpick/project.py
src/nitpick/style.py
src/nitpick/violations.py
tests/conftest.py
tests/helpers.py
tests/test_cli.py
tests/test_plugin.py
tests/test_pyproject_toml.py
tests/test_setup_cfg.py
tests/test_style.py

feat: apply changes to setup.cfg

---

docs/auto_detection.rst
docs/targets.rst
src/nitpick/constants.py
tests/helpers.py
tests/test_config.py

feat: root files for other programming languages

---

.github/pull_request_template.md
docs/configuration.rst
docs/generate_rst.py
docs/troubleshooting.rst
src/nitpick/cli.py
src/nitpick/constants.py
src/nitpick/plugins/pyproject_toml.py
src/nitpick/project.py
src/nitpick/violations.py
tests/conftest.py
tests/helpers.py
tests/test_config.py
tests/test_violations.py

feat: read configuration from `.nitpick.toml` or `pyproject.toml`

---

src/nitpick/constants.py
src/nitpick/flake8.py
src/nitpick/project.py
src/nitpick/violations.py
tests/helpers.py
tests/test_config.py
tests/test_project.py

- Fix error when no config file and no root file exist
- Add `nitpick-style.toml` as a root file

fix: don't abort when there is no config/root file

---

docs/examples.rst
styles/pre-commit/general.toml
styles/pre-commit/python.toml
tests/test_pre_commit.py

- This makes styles/pre-commit/general.toml more agnostic

chore: move python related pre-commit configuration to python.toml

---

docs/configuration.rst
docs/generate_rst.py
src/nitpick/generic.py
src/nitpick/style/core.py
src/nitpick/style/fetchers/__init__.py
src/nitpick/style/fetchers/github.py
src/nitpick/style/fetchers/http.py
tests/test_style.py

- support remote style urls of the form `gh://api_key@owner/repo/path.ext`
- support env-var expansion of auth info like `gh://$GH_AUTH_KEY@owner/repo/path` to avoid keeping secrets in plaintext config
- fix `?token=xxx` private repo access which has been [recently removed](https://github.blog/changelog/2021-04-19-sunsetting-api-authentication-via-query-parameters-and-the-oauth-applications-api/) (at least, I couldn't manage to make it work either in nitpick or with manual testing with HTTPie/curl). The fix works by converting a `token` query arg into the same format of credential as above, which is ultimately passed through `requests.get(..., auth=(KEY))`.

Feature support private gh styles

---

Makefile
docs/flake8_plugin.rst
src/nitpick/constants.py
src/nitpick/project.py
src/nitpick/style/core.py
src/nitpick/style/fetchers/pypackage.py
tests/test_project.py
tox.ini

Fixes #392 
- Use the current directory
- Don't climb the directory tree trying to find the project root

Use current dir and don't climb dirs to find the project root

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
README.rst
docs/generate_rst.py
docs/quickstart.rst

- `nitpick` = `nitpick fix` and it should be the default command
- keep `nitpick-fix` for compatibility
- See also:
- #161
- #166

feat: default pre-commit hook now runs "nitpick fix"

---

.pre-commit-config.yaml
docs/examples.rst
docs/generate_rst.py
docs/targets.rst
nitpick-style.toml
package.json
styles/commitizen.toml
styles/package-json.toml
styles/pre-commit/commitlint.toml
tasks.py
tests/test_json.py

Fixes #268.
- Simply replace the pre-commit hook for checking messages
- Keep `bumpversion` and changelog generation for now
- Bigger change with more effort involved: actually try to release on PyPI using GitHub Actions
- Remove the `update()` task from `tasks.py`; there is already a generic one in https://github.com/andreoliwa/conjuring/commit/3bf29d9b061439385b77ecbc47cc237274ab61e8

style: replace commitlint by commitizen

---

.github/workflows/python.yaml
.pre-commit-config.yaml
CHANGELOG.md
ci-prepare-cmd.sh
docs/examples.rst
docs/generate_rst.py
docs/ideas/yaml/contains.toml
docs/ideas/yaml/merge_lists/merged_style.toml
docs/ideas/yaml/merge_lists/py36.toml
docs/troubleshooting.rst
poetry.lock
pyproject.toml
setup.cfg
src/nitpick/resources/python/36.toml
src/nitpick/resources/python/github-workflow.toml
src/nitpick/resources/python/hooks.toml
src/nitpick/resources/python/stable.toml
src/nitpick/style/config.py
tests/test_style.py
tests/test_yaml/existing-actual.yaml
tests/test_yaml/existing-expected.yaml
tests/test_yaml/new-desired.toml
tests/test_yaml/new-expected.yaml
tests/test_yaml_pre_commit/real.yaml
tox.ini

- [PEP 494 -- Python 3.6 Release Schedule | Python.org](https://www.python.org/dev/peps/pep-0494/)
- [Python Release Python 3.6.0 | Python.org](https://www.python.org/downloads/release/python-360/)
- [Is Python 3.6 EOL? - Users - Discussions on Python.org](https://discuss.python.org/t/is-python-3-6-eol/12765)

feat: drop support for Python 3.6

---

src/nitpick/blender.py

Nothing really changed in this pull request.
I'm documenting the failed attempt.
1. https://github.com/sdispater/tomlkit preserves comments in the TOML file.
2. `uiri/toml` looks abandoned: https://github.com/uiri/toml/issues/361
3. I also briefly tried using https://github.com/hukkin/tomli; but it's read only, it doesn't write TOML. I would still need to use `tomlkit` or `uiri/toml` to write the file.
3. I couldn't easily remove empty tables from the output of `tomlkit.dumps()`. I raised the issue on https://github.com/sdispater/tomlkit/issues/166

docs: document attempt to keep only tomlkit

---

.pre-commit-config.yaml
src/nitpick/resources/shell/shellcheck.toml
tests/test_builtin/shell/shellcheck/.pre-commit-config.yaml

1. [shellcheck](https://github.com/koalaman/shellcheck) has to be installed on pre-commit.ci; trying [shellcheck-py](https://github.com/shellcheck-py/shellcheck-py) to do this job

ci: try to run shellcheck on pre-commit.ci

---

docs/autofix_docs.py
docs/styles.rst
poetry.lock
pyproject.toml
src/nitpick/constants.py
src/nitpick/style/core.py
src/nitpick/style/fetchers/__init__.py
src/nitpick/style/fetchers/base.py
src/nitpick/style/fetchers/file.py
src/nitpick/style/fetchers/github.py
src/nitpick/style/fetchers/http.py
src/nitpick/style/fetchers/pypackage.py
tasks.py
tests/test_cli.py
tests/test_style.py

1. The `GitHubURL` class should preserve query args.

fix: GitHub URL should preserve query args

---

docs/cli.rst
src/nitpick/cli.py

Fix these issue(s): #463
Uses the `@cli.version_option()` utility decorator to add a `--version` cli
switch:
```sh
$ nitpick --version
nitpick, version 0.31.0
```
I didn't add a test for this as it is a single line change; the click project
has this covered nicely already.

feat: add --version cli switch

---

poetry.lock
pyproject.toml
src/nitpick/style/cache.py
src/nitpick/style/fetchers/__init__.py
src/nitpick/style/fetchers/base.py
src/nitpick/style/fetchers/github.py
src/nitpick/style/fetchers/http.py
tests/test_cache.py

Fix #465 
Fix #466
Use `requests_cache.CachedSession()` for URL fetching and caching. file and
pypackage styles are no longer cached but reuse the original file each time.
This resolves issues with concurrent access to the cache; requests-cache is
robust in the face of multiple processes accessing the same on-disk cache data.
When encountering pickle data that can't be decoded, the cached data is
discarded and a new requests is made.

feat: switch to requests-cache for style caching

---

src/nitpick/style/fetchers/github.py
tests/test_style.py

You can't fetch the default branch for a private repo without a token.
Issues fixed by this pull request:
Fix #445

fix: Pass in token to fetch GH default branch

---

src/nitpick/project.py
src/nitpick/style/core.py
tests/test_project.py

There were two issues with the log output:
- It always claimed the configured styles came from pyproject.toml even when
.nitpick.toml is actually used.
- The chosen styles were shown as `<more_itertools.more.peekable object at 0x[hex address]>`

fix: actually show chosen styles in log output

---

.bumpversion.cfg
README.rst
docs/quickstart.rst
mega-linter-plugin-nitpick/nitpick.megalinter-descriptor.yml
package.json

This makes it possible to run nitpick as a [MegaLinter](https://megalinter.github.io/) step.
This installs a specific version of nitpick, so you can, in future, link to a
particular release and know it'll remain stable.

feat: Add MegaLinter plugin

---

.github/workflows/python.yaml
src/nitpick/generic.py
src/nitpick/style/core.py
src/nitpick/style/fetchers/__init__.py
src/nitpick/style/fetchers/base.py
src/nitpick/style/fetchers/file.py
tests/test_generic.py

- On Windows, reflection of file URLs to paths requires that we know about the URL hostname too as they could be UNC paths.
- Add some tests that verify that we are round-tripping from Path to URL and back again correctly.
- Simplify scheme testing for relative URLs, we only need to know about supported schemes.

fix: further improve file path handling

---

.pre-commit-config.yaml
.tool-versions
poetry.lock
src/nitpick/blender.py
src/nitpick/plugins/base.py
src/nitpick/style/fetchers/github.py

1. Upgrade pylint to fix a vulnerability: [PyUp Vuln #45185](https://pyup.io/vulnerabilities/PVE-2022-45185/45185/)
2. Upgrade Poetry to [Release 1.1.14 · python-poetry/poetry](https://github.com/python-poetry/poetry/releases/tag/1.1.14)

build: upgrade Poetry and pylint

---

poetry.lock
pyproject.toml

1. requests-cache v0.9.8 breaks things. See https://github.com/andreoliwa/nitpick/pull/518#discussion_r1152120390

fix(deps): pin requests-cache to >=1.0.0

---

.github/workflows/python.yaml
src/nitpick/resources/presets/nitpick.toml
src/nitpick/resources/python/github-workflow.toml
tests/test_builtin/python/github-workflow/.github/workflows/python.yaml

1. GitHub Actions workflow is not running on contributors' pull requests: https://github.com/andreoliwa/nitpick/pull/577
2. Run for both push and pull request but try to skip duplicates with https://github.com/marketplace/actions/skip-duplicate-actions
- ~~Add tests for the relevant parts:~~
- ~~API~~
- ~~CLI~~
- ~~`flake8` plugin (normal mode)~~
- ~~`flake8` plugin (offline mode)~~
- ~~Write documentation when there's a new API or functionality~~

ci: fix GitHub Actions workflow to run on contributors' pull requests

---

src/nitpick/plugins/toml.py
tests/test_toml.py

1. Changes to lists in TOML files should replace the list as is the case for YAML files

fix: fixed list changes in TOML files

---

README.rst
docs/configuration.rst
docs/quickstart.rst
src/nitpick/constants.py
src/nitpick/style/core.py
src/nitpick/violations.py
tests/helpers.py
tests/test_project.py
tests/test_violations.py

Issues fixed by this pull request:
Fix #491 
1. Fail when no style is explicitly configured.
2. Suggest to run `nitpick init` or do it manually.

fix: fail when no style is explicitly configured (don't use the default style)

---

.pre-commit-config.yaml
.prettierrc.toml
nitpick-style.toml
poetry.toml
pyproject.toml

1. Apply [toml-sort](https://github.com/pappasam/toml-sort) as suggested in https://github.com/andreoliwa/nitpick/issues/618.

style: apply toml-sort

---

src/nitpick/plugins/info.py

Issues fixed by this pull request:
- Fix #
1. Run identify on the actual file instead of only the filename. For example a file called [`justfile`](https://just.systems/man/en/introduction.html) wil get the tag `text` if you do but not if you run it on the filename

feat: Better file detection to allow more files with text plugin
